name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone
      run: ls -althrs

#    - name: Test Build
#      run: cargo build
#    - name: Test Cleanup
#      run: cargo clean


#    - name: Backup configs
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: if [[ -f /usr/share/myq/host.json ]]; then cp /usr/share/myq/host.json /root/host.json; fi
#
#    - name: Backup configs
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: if [[ -f /usr/share/myq/myq.yml ]]; then cp /usr/share/myq/myq.yml /root/myq.yml; fi

#
#    - name: Remove old build
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: rm -rf /usr/share/myq/target/release/
##
    - name: Copy repo contents
      uses: nogsantos/scp-deploy@master
      with:
        src: ./*
        host: root.koonts.net
        remote: /usr/share/airquality/
        port: 423
        user: root
        key: ${{ secrets.V1A_KEY }}
#
    - name: cargo build
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: cd /usr/share/airquality/ && /root/.cargo/bin/cargo build --release


    - name: npm build
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: cd /usr/share/airquality/airquality-web/ && npm install && npm run build

    - name: stop or create service
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: if [[ -f /etc/systemd/system/airquality.service ]]; then systemctl stop airquality; else echo "na"; fi

    - name: stop or create service
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: cp /usr/share/airquality/assets/airquality.service /etc/systemd/system/airquality.service && systemctl daemon-reload;


    - name: config
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: if [[ -f /usr/share/airquality/config/Settings.toml ]]; then cp /usr/share/airquality/config/Settings.toml /root/airquality_Settings.toml; else cp /usr/share/airquality/config/Settings_template.toml /usr/share/airquality/config/Settings.toml; fi


    - name: copy executable
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: cp /usr/share/airquality/target/release/air-quality /usr/share/airquality/air-quality

#    - name: copy assets
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: cp -r /usr/share/airquality/src/assets/* /usr/share/airquality/

#    - name: copy assets
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: cp /usr/share/airquality/airquality.service /usr/lib/systemd/system/airquality.service

    - name: copy assets
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: systemctl daemon-reload


#    - name: Restore configs
#      uses: JimCronqvist/action-ssh@master
#      with:
#        hosts: 'root@root.koonts.net:423'
#        privateKey: ${{ secrets.V1A_KEY }}
#        command: if [[ -f /root/host.json ]]; then cp /root/host.json /usr/share/myq/host.json; fi
#
    - name: config
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: if [[ -f /root/airquality_Settings.toml ]]; then cp /root/airquality_Settings.toml /usr/share/airquality/config/Settings.toml; else echo "na"; fi

    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@root.koonts.net:423'
        privateKey: ${{ secrets.V1A_KEY }}
        command: systemctl restart airquality
#        command: cd /usr/share/myq/ && /bin/bash -e start_docker.sh
